"""
EvidenceIQ Reports - PDF Builder
ReportLab-based PDF generation with watermarks and chain of custody.
"""
from typing import List, Dict, Any
from pathlib import Path
from datetime import datetime
from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    Image, PageBreak, KeepTogether
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.pdfgen import canvas

from app.config import settings


def create_watermark(canvas: canvas.Canvas, doc):
    """Draw watermark on every page."""
    canvas.saveState()
    canvas.setFont("Helvetica", 40)
    canvas.setFillColorRGB(0.9, 0.9, 0.9)
    canvas.translate(letter[0] / 2, letter[1] / 2)
    canvas.rotate(45)
    canvas.drawCentredString(0, 0, "CONFIDENTIAL")
    canvas.restoreState()


def build_evidence_report(
    case_name: str,
    generated_by: str,
    media_items: List[Dict[str, Any]],
    notes: Dict[str, str] = None
) -> BytesIO:
    """
    Build a PDF evidence report.
    
    Args:
        case_name: Name of the case/investigation
        generated_by: Name of user who generated the report
        media_items: List of media item data dicts
        notes: Optional dict of notes per media_id
    
    Returns:
        BytesIO buffer with PDF content
    """
    buffer = BytesIO()
    
    # Create document
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=72,
        leftMargin=72,
        topMargin=72,
        bottomMargin=18
    )
    
    # Container for elements
    elements = []
    
    # Styles
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Heading1"],
        fontSize=24,
        textColor=colors.HexColor("#1a1a1a"),
        spaceAfter=30,
        alignment=TA_CENTER
    )
    
    subtitle_style = ParagraphStyle(
        "CustomSubtitle",
        parent=styles["Normal"],
        fontSize=12,
        textColor=colors.HexColor("#666666"),
        alignment=TA_CENTER,
        spaceAfter=20
    )
    
    heading_style = ParagraphStyle(
        "CustomHeading",
        parent=styles["Heading2"],
        fontSize=14,
        textColor=colors.HexColor("#333333"),
        spaceAfter=12,
        spaceBefore=12
    )
    
    # Cover Page
    elements.append(Spacer(1, 1 * inch))
    
    # Add Logo if available
    logo_path = Path("static/logo.png")
    if logo_path.exists():
        try:
            logo = Image(str(logo_path), width=1.5 * inch, height=1.5 * inch)
            elements.append(logo)
            elements.append(Spacer(1, 0.2 * inch))
        except Exception:
            pass  # Fallback if image is invalid or unreadable
            
    elements.append(Paragraph("EvidenceIQ Report", title_style))
    elements.append(Spacer(1, 0.3 * inch))
    
    if case_name:
        elements.append(Paragraph(f"Case: {case_name}", subtitle_style))
    
    elements.append(Spacer(1, 0.5 * inch))
    
    # Cover info table
    cover_data = [
        ["Generated By:", generated_by],
        ["Generated At:", datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")],
        ["Total Items:", str(len(media_items))],
        ["Report ID:", f"RPT-{datetime.utcnow().strftime('%Y%m%d%H%M%S')}"],
    ]
    
    cover_table = Table(cover_data, colWidths=[2 * inch, 4 * inch])
    cover_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f0f0f0")),
        ("TEXTCOLOR", (0, 0), (-1, -1), colors.black),
        ("ALIGN", (0, 0), (0, -1), "LEFT"),
        ("ALIGN", (1, 0), (1, -1), "LEFT"),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("GRID", (0, 0), (-1, -1), 1, colors.grey),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    
    elements.append(cover_table)
    elements.append(PageBreak())
    
    # Item pages
    for idx, item in enumerate(media_items, 1):
        # Item heading
        elements.append(Paragraph(
            f"Item {idx} of {len(media_items)}: {item.get('original_filename', 'Unknown')}",
            heading_style
        ))
        
        # Thumbnail (if available)
        thumbnail_path = item.get('thumbnail_path')
        if thumbnail_path and Path(thumbnail_path).exists():
            try:
                img = Image(thumbnail_path, width=4 * inch, height=3 * inch)
                elements.append(img)
                elements.append(Spacer(1, 0.2 * inch))
            except Exception:
                pass
        
        # Item details table
        item_data = [
            ["Field", "Value"],
            ["UUID", item.get('uuid', 'N/A')],
            ["Classification", item.get('classification', 'Unknown')],
            ["Description", item.get('description', 'No description')[:200]],
            ["File Type", item.get('mime_type', 'Unknown')],
            ["File Size", f"{item.get('file_size_bytes', 0) / 1024 / 1024:.2f} MB"],
            ["SHA256 Hash", item.get('sha256_hash', 'N/A')[:32] + "..."],
            ["Processing Model", item.get('model_used', 'N/A')],
            ["Uploaded", str(item.get('upload_timestamp', 'Unknown'))],
        ]
        
        # Add dimensions if available
        if item.get('width_px') and item.get('height_px'):
            item_data.append(["Dimensions", f"{item['width_px']} x {item['height_px']}"])
        
        # Add notes if provided
        item_id = str(item.get('id', ''))
        if notes and item_id in notes:
            item_data.append(["Notes", notes[item_id]])
        
        item_table = Table(item_data, colWidths=[1.5 * inch, 4.5 * inch])
        item_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#333333")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("BACKGROUND", (0, 1), (0, -1), colors.HexColor("#f0f0f0")),
            ("TEXTCOLOR", (0, 1), (-1, -1), colors.black),
            ("ALIGN", (0, 0), (0, -1), "LEFT"),
            ("ALIGN", (1, 0), (1, -1), "LEFT"),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTNAME", (0, 1), (0, -1), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ]))
        
        elements.append(item_table)
        
        # Add page break between items (except last)
        if idx < len(media_items):
            elements.append(PageBreak())
    
    # Build PDF with watermark
    doc.build(elements, onFirstPage=create_watermark, onLaterPages=create_watermark)
    
    buffer.seek(0)
    return buffer


def generate_footer(canvas: canvas.Canvas, doc, generated_by: str):
    """Generate page footer."""
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.grey)
    
    # Footer text
    footer_text = f"Generated by {generated_by} | {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')} | Page {canvas.getPageNumber()}"
    canvas.drawString(72, 40, footer_text)
    
    canvas.restoreState()
