"""
EvidenceIQ Reports Router
Evidence report generation endpoints.
"""
from typing import List, Optional, Dict
from fastapi import APIRouter, Depends, HTTPException, status, Query, Request
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session

from app.database import get_db
from app.auth.dependencies import get_current_user, require_permissions
from app.users.models import User
from app.reports import service as reports_service

router = APIRouter(prefix="/reports", tags=["Reports"])


@router.post("/generate")
def generate_report(
    request: Request,
    media_ids: List[str] = Query(..., min_length=1, max_length=100),
    case_name: Optional[str] = Query(None, description="Case name for the report"),
    notes: Optional[Dict[str, str]] = None,
    db: Session = Depends(get_db),
    current_user: User = Depends(require_permissions({"export_report"}))
):
    """
    Generate an evidence report PDF.
    
    **Permissions:** Reviewer, Investigator, Admin
    
    **PDF Contents:**
    - Cover page: case name, generated by, timestamp, item count
    - Per item: thumbnail, classification, description, entity tags, EXIF summary, SHA256 hash
    - Watermark: "CONFIDENTIAL — EvidenceIQ" on every page
    - Footer: item index, generation timestamp, user who generated
    
    Chain of custody documentation for legal admissibility.
    """
    # Validate media items exist
    if not media_ids:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail={"error": "no_items", "message": "No media IDs provided"}
        )
    
    # Generate report
    pdf_buffer = reports_service.generate_evidence_report(
        db=db,
        media_ids=media_ids,
        case_name=case_name,
        notes=notes,
        generated_by=current_user.id,
        generated_by_name=current_user.username
    )
    
    # Filename
    filename = f"evidence_report_{case_name or 'unnamed'}_{current_user.username}.pdf"
    filename = filename.replace(" ", "_").replace("/", "_")
    
    return StreamingResponse(
        pdf_buffer,
        media_type="application/pdf",
        headers={
            "Content-Disposition": f"attachment; filename={filename}"
        }
    )


@router.post("/preview")
def preview_report(
    media_ids: List[str] = Query(..., min_length=1, max_length=100),
    case_name: Optional[str] = Query(None),
    db: Session = Depends(get_db),
    current_user: User = Depends(require_permissions({"export_report"}))
):
    """
    Preview report metadata without generating PDF.
    
    Returns statistics about what would be included in the report.
    """
    metadata = reports_service.get_report_metadata(
        db=db,
        media_ids=media_ids,
        case_name=case_name
    )
    
    return metadata
