/**
 * Report Detail Page
 * Report preview with CONFIDENTIAL watermark.
 */

"use client";

import { useParams } from "next/navigation";
import { ArrowLeft, Download } from "lucide-react";
import Link from "next/link";

import { useReport, useDownloadReport } from "@/lib/hooks/useReports";
import { formatDate } from "@/lib/utils/formatters";
import { mediaApi } from "@/lib/api/media";

import { PageHeader } from "@/components/layout/PageHeader";
import { FullPageSpinner } from "@/components/ui/FullPageSpinner";
import { HashDisplay } from "@/components/ui/HashDisplay";

export default function ReportDetailPage() {
  const params = useParams();
  const reportId = params.id as string;

  const { data: report, isLoading } = useReport(reportId);
  const downloadMutation = useDownloadReport();

  if (isLoading) {
    return <FullPageSpinner message="Loading report..." />;
  }

  if (!report) {
    return (
      <div className="text-center py-20">
        <p className="text-text-secondary">Report not found</p>
        <Link href="/reports" className="text-accent hover:underline mt-4 inline-block">
          Back to reports
        </Link>
      </div>
    );
  }

  return (
    <div className="relative">
      {/* CONFIDENTIAL Watermark */}
      <div className="confidential-stamp">CONFIDENTIAL</div>

      <PageHeader
        title={report.case_name}
        description={`Generated ${formatDate(report.generated_at)}`}
      >
        <div className="flex items-center gap-3">
          <Link
            href="/reports"
            className="flex items-center gap-2 text-text-secondary hover:text-text-primary transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            Back
          </Link>
          <button
            onClick={() => downloadMutation.mutate(reportId)}
            disabled={downloadMutation.isPending}
            className="flex items-center gap-2 px-4 py-2 bg-accent hover:bg-accent-hover text-background font-medium rounded-md transition-colors disabled:opacity-50"
          >
            {downloadMutation.isPending ? (
              <>
                <div className="w-4 h-4 border-2 border-background/30 border-t-background rounded-full animate-spin" />
                Downloading...
              </>
            ) : (
              <>
                <Download className="w-4 h-4" />
                Download PDF
              </>
            )}
          </button>
        </div>
      </PageHeader>

      {/* Report metadata */}
      <div className="bg-surface border border-border rounded-lg p-4 mb-6">
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm">
          <div>
            <p className="text-text-tertiary">Generated by</p>
            <p className="text-text-primary font-mono">{report.generated_by}</p>
          </div>
          <div>
            <p className="text-text-tertiary">Date</p>
            <p className="text-text-primary font-mono">{formatDate(report.generated_at)}</p>
          </div>
          <div>
            <p className="text-text-tertiary">Items</p>
            <p className="text-text-primary font-mono">{report.item_count}</p>
          </div>
          <div>
            <p className="text-text-tertiary">Report ID</p>
            <p className="text-text-primary font-mono">{report.id.slice(0, 8)}...</p>
          </div>
        </div>
      </div>

      {/* Report items */}
      <div className="space-y-6">
        {report.media_items?.map((item: any, index: number) => (
          <div
            key={item.media_id}
            className="bg-surface border border-border rounded-lg p-6"
          >
            <div className="flex items-center gap-2 text-text-tertiary text-sm mb-4">
              <span>Item {index + 1} of {report.item_count}</span>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              {/* Thumbnail */}
              <div className="aspect-video bg-surface-raised rounded overflow-hidden">
                <img
                  src={mediaApi.getMediaFileUrl(item.media_id)}
                  alt={item.filename}
                  className="w-full h-full object-cover"
                />
              </div>

              {/* Metadata */}
              <div className="md:col-span-2 space-y-3">
                <div>
                  <p className="text-text-tertiary text-xs uppercase">Filename</p>
                  <p className="text-text-primary">{item.filename}</p>
                </div>

                <div>
                  <p className="text-text-tertiary text-xs uppercase">SHA256 Hash</p>
                  <HashDisplay hash={item.sha256_hash} />
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <p className="text-text-tertiary text-xs uppercase">Type</p>
                    <p className="text-text-primary capitalize">{item.mime_type.split("/")[1]}</p>
                  </div>
                  <div>
                    <p className="text-text-tertiary text-xs uppercase">Uploaded</p>
                    <p className="text-text-primary">{formatDate(item.upload_timestamp)}</p>
                  </div>
                </div>

                {item.description && (
                  <div>
                    <p className="text-text-tertiary text-xs uppercase">Description</p>
                    <p className="text-text-primary">{item.description}</p>
                  </div>
                )}

                {item.note && (
                  <div className="bg-surface-raised rounded p-3">
                    <p className="text-text-tertiary text-xs uppercase mb-1">Note</p>
                    <p className="text-text-primary text-sm">{item.note}</p>
                  </div>
                )}
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
